version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine
    restart: always
    expose:
      - '5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    working_dir: /app
    env_file: .env.local
    ports:
      - '5432:5432'

  redis:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres:
