name: Deploy Development to Elastic Beanstalk

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t $DOCKER_USERNAME/muda .
          docker push $DOCKER_USERNAME/muda

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p docker muda --region $AWS_REGION
          eb use develop
          eb deploy --staged

    # - name: Generate deployment package
    #   run: zip -r deploy.zip . -x '*.git*' 'node_modules/*'

    # - name: Deploy to EB
    #   uses: einaregilsson/beanstalk-deploy@v22
    #   with:
    #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     application_name: scale-diary-server-develop
    #     environment_name: scale-diary-server-develop-env
    #     version_label: develop-${{ github.sha }}
    #     region: ap-northeast-2
    #     deployment_package: deploy.zip
